version: 2.1
jobs:
  lint:
    docker:
      - image: euantorano/zig:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run linter
          command: |
            zig fmt --check src/main.zig
  test_latest:
    docker:
      - image: archlinux:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: download zig version
          command: curl https://ziglang.org/download/0.9.0/zig-linux-x86_64-0.9.0.tar.xz > zig.tar.xz && tar xf zig.tar.xz
      - run:
          name: print zig version
          command: |
            PATH="$PATH:./zig-linux-x86_64-0.9.0"
            zig version
      - run:
          name: run tests
          command: |
            PATH="$PATH:./zig-linux-x86_64-0.9.0"
            zig build test
workflows:
  version: 2
  commit:
    jobs:
      - test_latest
      - lint
